export const optionMock = [
  "Dispatch Health",
  "Dispatch Health",
  "Dispatch Health",
  "Dispatch Health",
  "Dispatch Health",
  "Dispatch Health",
  "Dispatch Health",
  "Dispatch Health",
  "Dispatch Health",
  "Dispatch Health",
  "Dispatch Health",
  "Dispatch Health",
  "Dispatch Health",
  "Dispatch Health",
  "Dispatch Health",
  "Dispatch Health",
  "Dispatch Health",
  "Dispatch Health",
  "Dispatch Health",
];
