export const canadaProvinces = [
  {
    value: 446,
    label: "Alberta",
    id: 446,
    name: "Alberta",
    alternate_names: "AB",
    geoname_id: 5883102,
    geoname_code: "AB",
  },
  {
    value: 447,
    label: "British Columbia",
    id: 447,
    name: "British Columbia",
    alternate_names:
      "Col\\u00fambia Brit\\u00e2nica,BC,Columbia Brit\\u00e1nica,Kolumbia Brytyjska",
    geoname_id: 5909050,
    geoname_code: "BC",
  },
  {
    value: 448,
    label: "Manitoba",
    id: 448,
    name: "Manitoba",
    alternate_names: "MB",
    geoname_id: 6065171,
    geoname_code: "MB",
  },
  {
    value: 449,
    label: "New Brunswick",
    id: 449,
    name: "New Brunswick",
    alternate_names:
      "Nova Brunswick,Nova Brunsvique,NB,Nuevo Brunswick,Nowy Brunszwik",
    geoname_id: 6087430,
    geoname_code: "NB",
  },
  {
    value: 458,
    label: "Newfoundland and Labrador",
    id: 458,
    name: "Newfoundland and Labrador",
    alternate_names: "NL,New Foundland - Labrador,Terra Nova e Labrador",
    geoname_id: 6354959,
    geoname_code: "NL",
  },
  {
    value: 450,
    label: "Northwest Territories",
    id: 450,
    name: "Northwest Territories",
    alternate_names: "NT,Territ\\u00f3rios do Noroeste",
    geoname_id: 6091069,
    geoname_code: "NT",
  },
  {
    value: 451,
    label: "Nova Scotia",
    id: 451,
    name: "Nova Scotia",
    alternate_names: "Nova Esc\\u00f3cia,NS,Nueva Escocia,Nowa Szkocja",
    geoname_id: 6091530,
    geoname_code: "NS",
  },
  {
    value: 452,
    label: "Nunavut",
    id: 452,
    name: "Nunavut",
    alternate_names: "NU,Nunavute",
    geoname_id: 6091732,
    geoname_code: "NU",
  },
  {
    value: 453,
    label: "Ontario",
    id: 453,
    name: "Ontario",
    alternate_names: "ON,Ont\\u00e1rio",
    geoname_id: 6093943,
    geoname_code: "ON",
  },
  {
    value: 454,
    label: "Prince Edward Island",
    id: 454,
    name: "Prince Edward Island",
    alternate_names:
      "Ilha do Pr\\u00edncipe Eduardo,PE,Isla del Pr\\u00edncipe Eduardo,Wyspa Ksi\\u0119cia Edwarda",
    geoname_id: 6113358,
    geoname_code: "PEI",
  },
  {
    value: 455,
    label: "Quebec",
    id: 455,
    name: "Quebec",
    alternate_names: "QC,Quebeque",
    geoname_id: 6115047,
    geoname_code: "QC",
  },
  {
    value: 456,
    label: "Saskatchewan",
    id: 456,
    name: "Saskatchewan",
    alternate_names: "SK,Sascachev\\u00e3o",
    geoname_id: 6141242,
    geoname_code: "SK",
  },
  {
    value: 457,
    label: "Yukon",
    id: 457,
    name: "Yukon",
    alternate_names: "Iuc\\u00e3o,Yukon Territory,YT,Yuk\\u00f3n,Jukon",
    geoname_id: 6185811,
    geoname_code: "YT",
  },
];
