/* eslint-disable max-lines */
export enum AvailableCountry {
  CANADA = "canada",
  UNITED_STATE = "united states",
}

export const defaultCountry = {
  id: 234,
  name: "United States",
  iso3166: "US",
  government_number: {
    mask: "999-99-9999",
    placeholder: "123-45-6789",
  },
  phone: {
    mask: "(999) 999-9999",
    placeholder: "(202) 123-4567",
    code: 1,
  },
  postal: {
    mask: "99999",
    placeholder: "20510", //capitol hill
  },
  value: 234,
  label: "United States",
};

export const currentAvailableCountries = [
  {
    id: 234,
    name: "United States",
    iso3166: "US",
    government_number: {
      mask: "999-99-9999",
      placeholder: "123-45-6789",
    },
    phone: {
      mask: "(999) 999-9999",
      placeholder: "(202) 123-4567",
      code: 1,
    },
    postal: {
      mask: "99999",
      placeholder: "20510", //capitol hill
    },
    value: 234,
    label: "United States",
  },
  {
    id: 38,
    name: "Canada",
    iso3166: "CA",
    government_number: {
      mask: "999 999 999",
      placeholder: "123 456 789",
    },
    phone: {
      mask: "(999) 999-9999",
      placeholder: "(613) 123-4567",
      code: 1,
    },
    postal: {
      mask: "A9A 9A9",
      placeholder: "K1A 0A9", // parliament hill
    },
    value: 38,
    label: "Canada",
  },
  { name: "Mexico", id: 158, value: 158, label: "Mexico" },
];

export const countries = [
  {
    id: 234,
    name: "United States",
    iso3166: "US",
    government_number: {
      mask: "999-99-9999",
      placeholder: "123-45-6789",
    },
    phone: {
      mask: "(999) 999-9999",
      placeholder: "(202) 123-4567",
      code: 1,
    },
    postal: {
      mask: "99999",
      placeholder: "20510", //capitol hill
    },
    value: 234,
    label: "United States",
  },
  {
    id: 38,
    name: "Canada",
    iso3166: "CA",
    government_number: {
      mask: "999 999 999",
      placeholder: "123 456 789",
    },
    phone: {
      mask: "(999) 999-9999",
      placeholder: "(613) 123-4567",
      code: 1,
    },
    postal: {
      mask: "A9A 9A9",
      placeholder: "K1A 0A9", // parliament hill
    },
    value: 38,
    label: "Canada",
  },
  {
    name: "United Kingdom",
    id: 77,
    iso3166: "GB",
    government_number: {
      mask: "AA 99 99 99 A",
      placeholder: "AB 12 34 56 C",
    },
    phone: {
      mask: "09999 999 999",
      placeholder: "07123 123 456",
      code: 44,
      // 07123 123 456
    },
    postal: {
      mask: "Aw******?",
      placeholder: "A9A 9AA",
      // AA9A 9AA
      // A9A 9AA
      // A9 9AA
      // A99 9AA
      // AA9 9AA
      // AA99 9AA
    },
    value: 77,
    label: "United Kingdom",
  },
  { name: "Andorra", id: 1, value: 1, label: "Andorra" },
  {
    name: "United Arab Emirates",
    id: 2,
    value: 2,
    label: "United Arab Emirates",
  },
  { name: "Afghanistan", id: 3, value: 3, label: "Afghanistan" },
  {
    name: "Antigua and Barbuda",
    id: 4,
    value: 4,
    label: "Antigua and Barbuda",
  },
  { name: "Anguilla", id: 5, value: 5, label: "Anguilla" },
  { name: "Albania", id: 6, value: 6, label: "Albania" },
  { name: "Armenia", id: 7, value: 7, label: "Armenia" },
  { name: "Angola", id: 8, value: 8, label: "Angola" },
  { name: "Antarctica", id: 9, value: 9, label: "Antarctica" },
  { name: "Argentina", id: 10, value: 10, label: "Argentina" },
  {
    name: "American Samoa",
    id: 11,
    value: 11,
    label: "American Samoa",
  },
  { name: "Austria", id: 12, value: 12, label: "Austria" },
  { name: "Australia", id: 13, value: 13, label: "Australia" },
  { name: "Aruba", id: 14, value: 14, label: "Aruba" },
  { name: "Aland Islands", id: 15, value: 15, label: "Aland Islands" },
  { name: "Azerbaijan", id: 16, value: 16, label: "Azerbaijan" },
  {
    name: "Bosnia and Herzegovina",
    id: 17,
    value: 17,
    label: "Bosnia and Herzegovina",
  },
  { name: "Barbados", id: 18, value: 18, label: "Barbados" },
  { name: "Bangladesh", id: 19, value: 19, label: "Bangladesh" },
  { name: "Belgium", id: 20, value: 20, label: "Belgium" },
  { name: "Burkina Faso", id: 21, value: 21, label: "Burkina Faso" },
  { name: "Bulgaria", id: 22, value: 22, label: "Bulgaria" },
  { name: "Bahrain", id: 23, value: 23, label: "Bahrain" },
  { name: "Burundi", id: 24, value: 24, label: "Burundi" },
  { name: "Benin", id: 25, value: 25, label: "Benin" },
  {
    name: "Saint Barthelemy",
    id: 26,
    value: 26,
    label: "Saint Barthelemy",
  },
  { name: "Bermuda", id: 27, value: 27, label: "Bermuda" },
  { name: "Brunei", id: 28, value: 28, label: "Brunei" },
  { name: "Bolivia", id: 29, value: 29, label: "Bolivia" },
  {
    name: "Bonaire, Saint Eustatius and Saba",
    id: 30,
    value: 30,
    label: "Bonaire, Saint Eustatius and Saba",
  },
  { name: "Brazil", id: 31, value: 31, label: "Brazil" },
  { name: "Bahamas", id: 32, value: 32, label: "Bahamas" },
  { name: "Bhutan", id: 33, value: 33, label: "Bhutan" },
  { name: "Bouvet Island", id: 34, value: 34, label: "Bouvet Island" },
  { name: "Botswana", id: 35, value: 35, label: "Botswana" },
  { name: "Belarus", id: 36, value: 36, label: "Belarus" },
  { name: "Belize", id: 37, value: 37, label: "Belize" },
  { name: "Cocos Islands", id: 39, value: 39, label: "Cocos Islands" },
  {
    name: "Democratic Republic of the Congo",
    id: 40,
    value: 40,
    label: "Democratic Republic of the Congo",
  },
  {
    name: "Central African Republic",
    id: 41,
    value: 41,
    label: "Central African Republic",
  },
  {
    name: "Republic of the Congo",
    id: 42,
    value: 42,
    label: "Republic of the Congo",
  },
  { name: "Switzerland", id: 43, value: 43, label: "Switzerland" },
  { name: "Ivory Coast", id: 44, value: 44, label: "Ivory Coast" },
  { name: "Cook Islands", id: 45, value: 45, label: "Cook Islands" },
  { name: "Chile", id: 46, value: 46, label: "Chile" },
  { name: "Cameroon", id: 47, value: 47, label: "Cameroon" },
  { name: "China", id: 48, value: 48, label: "China" },
  { name: "Colombia", id: 49, value: 49, label: "Colombia" },
  { name: "Costa Rica", id: 50, value: 50, label: "Costa Rica" },
  { name: "Cuba", id: 51, value: 51, label: "Cuba" },
  { name: "Cape Verde", id: 52, value: 52, label: "Cape Verde" },
  { name: "Curacao", id: 53, value: 53, label: "Curacao" },
  {
    name: "Christmas Island",
    id: 54,
    value: 54,
    label: "Christmas Island",
  },
  { name: "Cyprus", id: 55, value: 55, label: "Cyprus" },
  {
    name: "Czech Republic",
    id: 56,
    value: 56,
    label: "Czech Republic",
  },
  { name: "Germany", id: 57, value: 57, label: "Germany" },
  { name: "Djibouti", id: 58, value: 58, label: "Djibouti" },
  { name: "Denmark", id: 59, value: 59, label: "Denmark" },
  { name: "Dominica", id: 60, value: 60, label: "Dominica" },
  {
    name: "Dominican Republic",
    id: 61,
    value: 61,
    label: "Dominican Republic",
  },
  { name: "Algeria", id: 62, value: 62, label: "Algeria" },
  { name: "Ecuador", id: 63, value: 63, label: "Ecuador" },
  { name: "Estonia", id: 64, value: 64, label: "Estonia" },
  { name: "Egypt", id: 65, value: 65, label: "Egypt" },
  {
    name: "Western Sahara",
    id: 66,
    value: 66,
    label: "Western Sahara",
  },
  { name: "Eritrea", id: 67, value: 67, label: "Eritrea" },
  { name: "Spain", id: 68, value: 68, label: "Spain" },
  { name: "Ethiopia", id: 69, value: 69, label: "Ethiopia" },
  { name: "Finland", id: 70, value: 70, label: "Finland" },
  { name: "Fiji", id: 71, value: 71, label: "Fiji" },
  {
    name: "Falkland Islands",
    id: 72,
    value: 72,
    label: "Falkland Islands",
  },
  { name: "Micronesia", id: 73, value: 73, label: "Micronesia" },
  { name: "Faroe Islands", id: 74, value: 74, label: "Faroe Islands" },
  { name: "France", id: 75, value: 75, label: "France" },
  { name: "Gabon", id: 76, value: 76, label: "Gabon" },
  { name: "Grenada", id: 78, value: 78, label: "Grenada" },
  { name: "Georgia", id: 79, value: 79, label: "Georgia" },
  { name: "French Guiana", id: 80, value: 80, label: "French Guiana" },
  { name: "Guernsey", id: 81, value: 81, label: "Guernsey" },
  { name: "Ghana", id: 82, value: 82, label: "Ghana" },
  { name: "Gibraltar", id: 83, value: 83, label: "Gibraltar" },
  { name: "Greenland", id: 84, value: 84, label: "Greenland" },
  { name: "Gambia", id: 85, value: 85, label: "Gambia" },
  { name: "Guinea", id: 86, value: 86, label: "Guinea" },
  { name: "Guadeloupe", id: 87, value: 87, label: "Guadeloupe" },
  {
    name: "Equatorial Guinea",
    id: 88,
    value: 88,
    label: "Equatorial Guinea",
  },
  { name: "Greece", id: 89, value: 89, label: "Greece" },
  {
    name: "South Georgia and the South Sandwich Islands",
    id: 90,
    value: 90,
    label: "South Georgia and the South Sandwich Islands",
  },
  { name: "Guatemala", id: 91, value: 91, label: "Guatemala" },
  { name: "Guam", id: 92, value: 92, label: "Guam" },
  { name: "Guinea-Bissau", id: 93, value: 93, label: "Guinea-Bissau" },
  { name: "Guyana", id: 94, value: 94, label: "Guyana" },
  { name: "Hong Kong", id: 95, value: 95, label: "Hong Kong" },
  {
    name: "Heard Island and McDonald Islands",
    id: 96,
    value: 96,
    label: "Heard Island and McDonald Islands",
  },
  { name: "Honduras", id: 97, value: 97, label: "Honduras" },
  { name: "Croatia", id: 98, value: 98, label: "Croatia" },
  { name: "Haiti", id: 99, value: 99, label: "Haiti" },
  { name: "Hungary", id: 100, value: 100, label: "Hungary" },
  { name: "Indonesia", id: 101, value: 101, label: "Indonesia" },
  { name: "Ireland", id: 102, value: 102, label: "Ireland" },
  { name: "Israel", id: 103, value: 103, label: "Israel" },
  { name: "Isle of Man", id: 104, value: 104, label: "Isle of Man" },
  { name: "India", id: 105, value: 105, label: "India" },
  {
    name: "British Indian Ocean Territory",
    id: 106,
    value: 106,
    label: "British Indian Ocean Territory",
  },
  { name: "Iraq", id: 107, value: 107, label: "Iraq" },
  { name: "Iran", id: 108, value: 108, label: "Iran" },
  { name: "Iceland", id: 109, value: 109, label: "Iceland" },
  { name: "Italy", id: 110, value: 110, label: "Italy" },
  { name: "Jersey", id: 111, value: 111, label: "Jersey" },
  { name: "Jamaica", id: 112, value: 112, label: "Jamaica" },
  { name: "Jordan", id: 113, value: 113, label: "Jordan" },
  { name: "Japan", id: 114, value: 114, label: "Japan" },
  { name: "Kenya", id: 115, value: 115, label: "Kenya" },
  { name: "Kyrgyzstan", id: 116, value: 116, label: "Kyrgyzstan" },
  { name: "Cambodia", id: 117, value: 117, label: "Cambodia" },
  { name: "Kiribati", id: 118, value: 118, label: "Kiribati" },
  { name: "Comoros", id: 119, value: 119, label: "Comoros" },
  {
    name: "Saint Kitts and Nevis",
    id: 120,
    value: 120,
    label: "Saint Kitts and Nevis",
  },
  { name: "North Korea", id: 121, value: 121, label: "North Korea" },
  { name: "South Korea", id: 122, value: 122, label: "South Korea" },
  { name: "Kosovo", id: 123, value: 123, label: "Kosovo" },
  { name: "Kuwait", id: 124, value: 124, label: "Kuwait" },
  {
    name: "Cayman Islands",
    id: 125,
    value: 125,
    label: "Cayman Islands",
  },
  { name: "Kazakhstan", id: 126, value: 126, label: "Kazakhstan" },
  { name: "Laos", id: 127, value: 127, label: "Laos" },
  { name: "Lebanon", id: 128, value: 128, label: "Lebanon" },
  { name: "Saint Lucia", id: 129, value: 129, label: "Saint Lucia" },
  {
    name: "Liechtenstein",
    id: 130,
    value: 130,
    label: "Liechtenstein",
  },
  { name: "Sri Lanka", id: 131, value: 131, label: "Sri Lanka" },
  { name: "Liberia", id: 132, value: 132, label: "Liberia" },
  { name: "Lesotho", id: 133, value: 133, label: "Lesotho" },
  { name: "Lithuania", id: 134, value: 134, label: "Lithuania" },
  { name: "Luxembourg", id: 135, value: 135, label: "Luxembourg" },
  { name: "Latvia", id: 136, value: 136, label: "Latvia" },
  { name: "Libya", id: 137, value: 137, label: "Libya" },
  { name: "Morocco", id: 138, value: 138, label: "Morocco" },
  { name: "Monaco", id: 139, value: 139, label: "Monaco" },
  { name: "Moldova", id: 140, value: 140, label: "Moldova" },
  { name: "Montenegro", id: 141, value: 141, label: "Montenegro" },
  { name: "Saint Martin", id: 142, value: 142, label: "Saint Martin" },
  { name: "Madagascar", id: 143, value: 143, label: "Madagascar" },
  {
    name: "Marshall Islands",
    id: 144,
    value: 144,
    label: "Marshall Islands",
  },
  { name: "Macedonia", id: 145, value: 145, label: "Macedonia" },
  { name: "Mali", id: 146, value: 146, label: "Mali" },
  { name: "Myanmar", id: 147, value: 147, label: "Myanmar" },
  { name: "Mongolia", id: 148, value: 148, label: "Mongolia" },
  { name: "Macao", id: 149, value: 149, label: "Macao" },
  {
    name: "Northern Mariana Islands",
    id: 150,
    value: 150,
    label: "Northern Mariana Islands",
  },
  { name: "Martinique", id: 151, value: 151, label: "Martinique" },
  { name: "Mauritania", id: 152, value: 152, label: "Mauritania" },
  { name: "Montserrat", id: 153, value: 153, label: "Montserrat" },
  { name: "Malta", id: 154, value: 154, label: "Malta" },
  { name: "Mauritius", id: 155, value: 155, label: "Mauritius" },
  { name: "Maldives", id: 156, value: 156, label: "Maldives" },
  { name: "Malawi", id: 157, value: 157, label: "Malawi" },
  { name: "Mexico", id: 158, value: 158, label: "Mexico" },
  { name: "Malaysia", id: 159, value: 159, label: "Malaysia" },
  { name: "Mozambique", id: 160, value: 160, label: "Mozambique" },
  { name: "Namibia", id: 161, value: 161, label: "Namibia" },
  {
    name: "New Caledonia",
    id: 162,
    value: 162,
    label: "New Caledonia",
  },
  { name: "Niger", id: 163, value: 163, label: "Niger" },
  {
    name: "Norfolk Island",
    id: 164,
    value: 164,
    label: "Norfolk Island",
  },
  { name: "Nigeria", id: 165, value: 165, label: "Nigeria" },
  { name: "Nicaragua", id: 166, value: 166, label: "Nicaragua" },
  { name: "Netherlands", id: 167, value: 167, label: "Netherlands" },
  { name: "Norway", id: 168, value: 168, label: "Norway" },
  { name: "Nepal", id: 169, value: 169, label: "Nepal" },
  { name: "Nauru", id: 170, value: 170, label: "Nauru" },
  { name: "Niue", id: 171, value: 171, label: "Niue" },
  { name: "New Zealand", id: 172, value: 172, label: "New Zealand" },
  { name: "Oman", id: 173, value: 173, label: "Oman" },
  { name: "Panama", id: 174, value: 174, label: "Panama" },
  { name: "Peru", id: 175, value: 175, label: "Peru" },
  {
    name: "French Polynesia",
    id: 176,
    value: 176,
    label: "French Polynesia",
  },
  {
    name: "Papua New Guinea",
    id: 177,
    value: 177,
    label: "Papua New Guinea",
  },
  { name: "Philippines", id: 178, value: 178, label: "Philippines" },
  { name: "Pakistan", id: 179, value: 179, label: "Pakistan" },
  { name: "Poland", id: 180, value: 180, label: "Poland" },
  {
    name: "Saint Pierre and Miquelon",
    id: 181,
    value: 181,
    label: "Saint Pierre and Miquelon",
  },
  { name: "Pitcairn", id: 182, value: 182, label: "Pitcairn" },
  {
    name: "Puerto Rico",
    id: 183,
    iso3166: "PRI",
    government_number: {
      mask: "999-99-9999",
      placeholder: "123-45-6789",
    },
    phone: {
      mask: "(999) 999-9999",
      placeholder: "(202) 123-4567",
      code: 1,
    },
    postal: {
      mask: "99999",
      placeholder: "20510", //capitol hill
    },
    value: 183,
    label: "Puerto Rico",
  },
  {
    name: "Palestinian Territory",
    id: 184,
    value: 184,
    label: "Palestinian Territory",
  },
  { name: "Portugal", id: 185, value: 185, label: "Portugal" },
  { name: "Palau", id: 186, value: 186, label: "Palau" },
  { name: "Paraguay", id: 187, value: 187, label: "Paraguay" },
  { name: "Qatar", id: 188, value: 188, label: "Qatar" },
  { name: "Reunion", id: 189, value: 189, label: "Reunion" },
  { name: "Romania", id: 190, value: 190, label: "Romania" },
  { name: "Serbia", id: 191, value: 191, label: "Serbia" },
  { name: "Russia", id: 192, value: 192, label: "Russia" },
  { name: "Rwanda", id: 193, value: 193, label: "Rwanda" },
  { name: "Saudi Arabia", id: 194, value: 194, label: "Saudi Arabia" },
  {
    name: "Solomon Islands",
    id: 195,
    value: 195,
    label: "Solomon Islands",
  },
  { name: "Seychelles", id: 196, value: 196, label: "Seychelles" },
  { name: "Sudan", id: 197, value: 197, label: "Sudan" },
  { name: "South Sudan", id: 198, value: 198, label: "South Sudan" },
  { name: "Sweden", id: 199, value: 199, label: "Sweden" },
  { name: "Singapore", id: 200, value: 200, label: "Singapore" },
  { name: "Saint Helena", id: 201, value: 201, label: "Saint Helena" },
  { name: "Slovenia", id: 202, value: 202, label: "Slovenia" },
  {
    name: "Svalbard and Jan Mayen",
    id: 203,
    value: 203,
    label: "Svalbard and Jan Mayen",
  },
  { name: "Slovakia", id: 204, value: 204, label: "Slovakia" },
  { name: "Sierra Leone", id: 205, value: 205, label: "Sierra Leone" },
  { name: "San Marino", id: 206, value: 206, label: "San Marino" },
  { name: "Senegal", id: 207, value: 207, label: "Senegal" },
  { name: "Somalia", id: 208, value: 208, label: "Somalia" },
  { name: "Suriname", id: 209, value: 209, label: "Suriname" },
  {
    name: "Sao Tome and Principe",
    id: 210,
    value: 210,
    label: "Sao Tome and Principe",
  },
  { name: "El Salvador", id: 211, value: 211, label: "El Salvador" },
  { name: "Sint Maarten", id: 212, value: 212, label: "Sint Maarten" },
  { name: "Syria", id: 213, value: 213, label: "Syria" },
  { name: "Swaziland", id: 214, value: 214, label: "Swaziland" },
  {
    name: "Turks and Caicos Islands",
    id: 215,
    value: 215,
    label: "Turks and Caicos Islands",
  },
  { name: "Chad", id: 216, value: 216, label: "Chad" },
  {
    name: "French Southern Territories",
    id: 217,
    value: 217,
    label: "French Southern Territories",
  },
  { name: "Togo", id: 218, value: 218, label: "Togo" },
  { name: "Thailand", id: 219, value: 219, label: "Thailand" },
  { name: "Tajikistan", id: 220, value: 220, label: "Tajikistan" },
  { name: "Tokelau", id: 221, value: 221, label: "Tokelau" },
  { name: "East Timor", id: 222, value: 222, label: "East Timor" },
  { name: "Turkmenistan", id: 223, value: 223, label: "Turkmenistan" },
  { name: "Tunisia", id: 224, value: 224, label: "Tunisia" },
  { name: "Tonga", id: 225, value: 225, label: "Tonga" },
  { name: "Turkey", id: 226, value: 226, label: "Turkey" },
  {
    name: "Trinidad and Tobago",
    id: 227,
    value: 227,
    label: "Trinidad and Tobago",
  },
  { name: "Tuvalu", id: 228, value: 228, label: "Tuvalu" },
  { name: "Taiwan", id: 229, value: 229, label: "Taiwan" },
  { name: "Tanzania", id: 230, value: 230, label: "Tanzania" },
  { name: "Ukraine", id: 231, value: 231, label: "Ukraine" },
  { name: "Uganda", id: 232, value: 232, label: "Uganda" },
  {
    name: "United States Minor Outlying Islands",
    id: 233,
    value: 233,
    label: "United States Minor Outlying Islands",
  },
  { name: "Uruguay", id: 235, value: 235, label: "Uruguay" },
  { name: "Uzbekistan", id: 236, value: 236, label: "Uzbekistan" },
  { name: "Vatican", id: 237, value: 237, label: "Vatican" },
  {
    name: "Saint Vincent and the Grenadines",
    id: 238,
    value: 238,
    label: "Saint Vincent and the Grenadines",
  },
  { name: "Venezuela", id: 239, value: 239, label: "Venezuela" },
  {
    name: "British Virgin Islands",
    id: 240,
    value: 240,
    label: "British Virgin Islands",
  },
  {
    name: "U.S. Virgin Islands",
    id: 241,
    value: 241,
    label: "U.S. Virgin Islands",
  },
  { name: "Vietnam", id: 242, value: 242, label: "Vietnam" },
  { name: "Vanuatu", id: 243, value: 243, label: "Vanuatu" },
  {
    name: "Wallis and Futuna",
    id: 244,
    value: 244,
    label: "Wallis and Futuna",
  },
  { name: "Samoa", id: 245, value: 245, label: "Samoa" },
  { name: "Yemen", id: 246, value: 246, label: "Yemen" },
  { name: "Mayotte", id: 247, value: 247, label: "Mayotte" },
  { name: "South Africa", id: 248, value: 248, label: "South Africa" },
  { name: "Zambia", id: 249, value: 249, label: "Zambia" },
  { name: "Zimbabwe", id: 250, value: 250, label: "Zimbabwe" },
  {
    name: "Serbia and Montenegro",
    id: 251,
    value: 251,
    label: "Serbia and Montenegro",
  },
  {
    name: "Netherlands Antilles",
    id: 252,
    value: 252,
    label: "Netherlands Antilles",
  },
];
