export const EmptyAdvisor = {
  amount: 0,
  amount_children: 0,
  amount_employee: 0,
  amount_family: 0,
  amount_number: 0,
  amount_spouse: 0,
  amount_text: "",
  amount_type: "fixed_per_employee_per_month",
  fee_type: "",
  group_size_amount: [],
  id: "",
  name: "",
};

export const EmptyStopLoss = {
  aggregate_attachment_percent: 0,
  aggregate_stop_loss_underwriting_factor: 0,
  aggregate_tlo: false,
  aggregating_specific_deductible: 0,
  claims_fund_underwriting_factor: 0,
  contract_length: "",
  contract_length_agg: "",
  contract_length_spec: "",
  created: "",
  date_underwritten_rates_set: 0,
  display_name: "",
  fees: [],
  files: {},
  has_advanced_specific_funding: false,
  has_agg_accommodation: false,
  id: "",
  is_blended: false,
  lasers: [],
  modified: "",
  name: "",
  network_discount_override: 0,
  network_ingredients: [],
  notes: "",
  number_of_tiers: 0,
  org_plans: [],
  overall_underwriting_factor: 0,
  proposal_documents: [],
  run_in: 0,
  run_out: 0,
  specific_deductible: 0,
  specific_stop_loss_underwriting_factor: 0,
  specific_tlo: false,
  status: "",
  stop_loss_carrier: null,
  stop_loss_contract: "",
  stop_loss_title: "",
  underwritten_status: "",
  version_type: "",
};
