import { IMedicalPlan } from "src/interfaces/orgRecipes";

export const EmptyPlan: IMedicalPlan = {
  id: "",
  plan_set: "",
  participation_estimation_employee: 0,
  participation_estimation_employee_child: 0,
  participation_estimation_employee_family: 0,
  participation_estimation_employee_spouse: 0,
  medical_plan: {
    name: "",
    carrier: null,
    type: "8fc8da2d-7d67-4fa4-a2a5-47df974d8ee4", //medical
    description: "",
    in_network_url: "",
    code: "",
    network: null,
    custom: true,
    level: "",
    hsa_qualified: false,
    plan_class: "PPO",
    deductible_in: 0,
    deductible_out: 0,
    deductible_family_in: 0,
    deductible_family_out: 0,
    out_of_pocket_max_in: 0,
    out_of_pocket_max_out: 0,
    out_of_pocket_max_family_in: 0,
    out_of_pocket_max_family_out: 0,
    coinsurance_in: 0,
    coinsurance_out: 0,
    copay_office_visit: null,
    copay_office_visit_type: "deductible_coinsurance",
    copay_office_visit_max: null,
    copay_emergency_room: null,
    copay_emergency_room_type: "deductible_coinsurance",
    copay_emergency_room_max: null,
    copay_ambulatory: null,
    copay_ambulatory_type: "deductible_coinsurance",
    copay_ambulatory_max: null,
    copay_specialist: null,
    copay_specialist_type: "deductible_coinsurance",
    copay_specialist_max: null,
    copay_urgent_care: null,
    copay_urgent_care_type: "deductible_coinsurance",
    copay_urgent_care_max: null,
    copay_hospital: null,
    copay_hospital_type: "deductible_coinsurance",
    copay_hospital_max: null,
    rx_generic: null,
    rx_generic_type: "",
    rx_generic_max: null,
    rx_generic_str: "Ded/Coins",
    rx_preferred: null,
    rx_preferred_type: "",
    rx_preferred_max: null,
    rx_preferred_str: "Ded/Coins",
    rx_non_preferred: null,
    rx_non_preferred_type: "",
    rx_non_preferred_max: null,
    rx_non_preferred_str: "Ded/Coins",
    rx_specialty: null,
    rx_specialty_type: "",
    rx_specialty_max: null,
    rx_specialty_str: "Ded/Coins",
    rx_preventative: null,
    rx_preventative_type: "",
    rx_preventative_max: null,
    rx_preventative_str: "Ded/Coins",
    rx_deductible: null,
    rx_deductible_str: "Integrated to Medical",
    rx_tier: "",
  },
};
